version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./chessmatch_api:/chessmatch
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 main.py
             alembic upgrade head"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chessmatch
      - DB_HOST=pgdb
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    
    depends_on:
      - pgdb
      - redis
      - celery_worker

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=chessmatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6389:6379"

  celery_worker:
    build: .
    command: celery --app=celery worker -l INFO
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis


volumes:
  pgdata:
