version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - .:/chessmatch
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head
             python3 main.py"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chessmatch
      - DB_HOST=pgdb
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      pgdb:
        condition: service_healthy
      

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=chessmatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chessmatch"]
      interval: 2s
      timeout: 2s
      retries: 5
      

volumes:
  pgdata:
